version: "3"

services:
  api:
    build: .
    command: npm run start
    ports:
      - '8080:8080'
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - ./test:/usr/src/app/test
      - ./package.json:/usr/src/app/package.json
    depends_on:
      - postgresql
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: justauser 
      POSTGRES_PASSWORD: somerandompassword 
      POSTGRES_DB: dev_database
    ports:
      - '5432:5432'
